stages:
  - build

build_frontend:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - while ! docker info > /dev/null 2>&1; do echo "Waiting for Docker daemon..."; sleep 1; done
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/gfdd-web:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/gfdd-web:$CI_COMMIT_SHORT_SHA
