[{'filename': 'sample3.jpg', 'filepath': 'C:\\Users\\PILR\\AppData\\Local\\Temp\\tmpr4jc9zfs\\sample3.jpg',

  'filesize': 14689, 'type': 'image/jpeg', 'pages':
      [{'page': 1, 'text_content': '', 'analysis':
          {'pca': {'alert': 1, 'pca_components': None, 'cluster_analysis': None},
           'stats': {'alerts': [{'mode': 'minimum', 'alert_type': ['blue', 'green', 'bimodal_distribution'], 'message': [' Parts of the image are too dark or missing colors', ' Multiple patterns or changes are detected']}, {'mode': 'average', 'alert_type': ['blue', 'red', 'bimodal_distribution'], 'message': [' Colors differ more than expected', ' Multiple patterns or changes are detected']}, {'mode': 'maximum', 'alert_type': ['blue', 'bimodal_distribution'], 'message': [' One color dominates the image', ' Multiple patterns or changes are detected']}], 'intensity': {}},
           'detection': {'model': None, 'confidence': None, 'result': 'AI'}, 'echo': []}, 'detection_status': 'processed'}],
  'analysis': {'component': '#1', 'module_name': 'Pixel & AI Analysis', 'alert_summary': [' Parts of the image are too dark or missing colors', ' Multiple patterns or changes are detected', ' Colors differ more than expected', ' One color dominates the image', '98.40% likelihood that the image was created by AI', ' There is a high contrast difference', ' Unusual data pattern detected, possible tampering'], 'is_potential_fraud': 'yes'}, 'document_id': 69},

 {'filename': 'sample2.png', 'filepath': 'C:\\Users\\PILR\\AppData\\Local\\Temp\\tmpr4jc9zfs\\sample2.png', 'filesize': 30745, 'type': 'image/png', 'pages': [{'page': 1, 'text_content': '', 'analysis': {'pca': {'alert': 1, 'pca_components': None, 'cluster_analysis': None}, 'stats': {'alerts': [{'mode': 'minimum', 'alert_type': ['blue', 'green'], 'message': [' Parts of the image are too dark or missing colors']}, {'mode': 'average', 'alert_type': ['blue', 'red'], 'message': [' Colors differ more than expected']}, {'mode': 'maximum', 'alert_type': ['blue'], 'message': [' One color dominates the image']}], 'intensity': {}}, 'detection': {'model': None, 'confidence': None, 'result': 'AI'}, 'echo': []}, 'detection_status': 'processed'}], 'analysis': {'component': '#1', 'module_name': 'Pixel & AI Analysis', 'alert_summary': [' Parts of the image are too dark or missing colors', ' Colors differ more than expected', ' One color dominates the image', '81.33% likelihood that the image was created by AI', ' There is a high contrast difference', ' One color channel is overemphasized', ' Possible signs that content is fake or altered', 'Editing software was detected.'], 'is_potential_fraud': 'yes'}, 'document_id': 70}, {'filename': 'sample1.png', 'filepath': 'C:\\Users\\PILR\\AppData\\Local\\Temp\\tmpr4jc9zfs\\sample1.png', 'filesize': 7474, 'type': 'image/png', 'pages': [{'page': 1, 'text_content': '', 'analysis': {'pca': {'alert': 1, 'pca_components': None, 'cluster_analysis': None}, 'stats': {'alerts': [{'mode': 'minimum', 'alert_type': ['blue', 'green'], 'message': [' Parts of the image are too dark or missing colors']}, {'mode': 'average', 'alert_type': ['blue', 'red'], 'message': [' Colors differ more than expected']}, {'mode': 'maximum', 'alert_type': ['blue'], 'message': [' One color dominates the image']}], 'intensity': {}}, 'detection': {'model': None, 'confidence': None, 'result': 'AI'}, 'echo': []}, 'detection_status': 'processed'}], 'analysis': {'component': '#1', 'module_name': 'Pixel & AI Analysis', 'alert_summary': [' Parts of the image are too dark or missing colors', ' Colors differ more than expected', ' One color dominates the image', '90.24% likelihood that the image was created by AI', ' There is a high contrast difference', ' One color channel is overemphasized', ' Possible signs that content is fake or altered', 'Editing software was detected.'], 'is_potential_fraud': 'yes'}, 'document_id': 71}]