from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import torch
from PIL import Image
from transformers import ViTFeatureExtractor, AutoModelForImageClassification, AutoImageProcessor
import torch.nn.functional as F
import os

# 常量定义
THRESHOLD = 0.75
MODEL_DIR = "Model/AIorNot"
#MODEL_NAME = "dima806/ai_image_detector"  # 改用更可靠的模型
MODEL_NAME = "Nahrawy/AIorNot"
# Models
class DetectionResult(BaseModel):
    filename: str
    result: str
    real_prob: float
    ai_prob: float
    alert: int = 0
    alert_message: str = ""

class BatchDetectionResult(BaseModel):
    results: List[DetectionResult]
    total_files: int
    human_count: int
    ai_count: int

class PDFDetectionResult(BaseModel):
    pdf_filename: str
    images: List[DetectionResult]
    human_count: int
    ai_count: int
    total_images: int

# Initialize model (load once at startup)
# 初始化模型（优化缓存逻辑）

def load_models():
    """安全加载模型"""
    """安全加载模型（Linux/Win通用）"""
    # 1. 显式验证本地路径
    model_exists = all([
        os.path.exists(MODEL_DIR),
        os.path.exists(os.path.join(MODEL_DIR, "config.json")),
        os.path.exists(os.path.join(MODEL_DIR, "preprocessor_config.json"))
    ])
    
    if model_exists:
        try:
            # 强制本地加载 + 详细错误跟踪
            processor = AutoImageProcessor.from_pretrained(
                MODEL_DIR, 
                local_files_only=True
            )
            model = AutoModelForImageClassification.from_pretrained(
                MODEL_DIR,
                local_files_only=True
            )
            print(f"✅ 从本地加载成功: {MODEL_DIR}")

            
        except OSError as e:
            # 3. 精准捕获本地加载错误
            print(f"⚠️ 本地模型不完整: {e}")
            # 显示具体缺失文件
            print(f"目录内容: {os.listdir(MODEL_DIR)}")
    try:
        processor = AutoImageProcessor.from_pretrained(MODEL_DIR)
        model = AutoModelForImageClassification.from_pretrained(MODEL_DIR)
        print("✅ 从本地加载模型")
    except Exception as e:
        print(f"⚠️ 本地模型不存在: {e}，下载中...")
        processor = AutoImageProcessor.from_pretrained(MODEL_NAME)
        model = AutoModelForImageClassification.from_pretrained(MODEL_NAME)
        os.makedirs(MODEL_DIR, exist_ok=True)
        processor.save_pretrained(MODEL_DIR)
        model.save_pretrained(MODEL_DIR)
    
    # 验证标签顺序
    id2label = model.config.id2label
    if sorted(id2label.values()) != sorted(["real", "ai"]):
        print(f"⚠️ 意外标签: {id2label}")
    
    return processor, model, id2label

# 全局初始化
image_processor, detection_model, label_map = load_models()
# 核心检测函数
def detect_ai_image(image_path: str):
    # 图像预处理
    image = Image.open(image_path).convert("RGB")
    
    # 模型推理
    inputs = image_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = detection_model(**inputs)
    
    # 概率解析
    probs = F.softmax(outputs.logits, dim=-1)[0]
    real_prob = probs[detection_model.config.label2id["real"]].item()
    ai_prob = probs[detection_model.config.label2id["ai"]].item()
    
    # 阈值判定
    alert, result = determine_alert_level(real_prob, ai_prob)
    
    # 警报消息
    alert_msg = generate_alert_message(alert, ai_prob)
    
    return {
        "result": result,
        "real_prob": float(real_prob),
        "ai_prob": float(ai_prob),
        "alert":alert,
        "alert_message":alert_msg
    }

    '''
    return DetectionResult(
        filename=image_path,
        result=result,
        real_prob=real_prob,
        ai_prob=ai_prob,
        alert=alert,
        alert_message=alert_msg
    )
    '''

# 辅助函数
def determine_alert_level(real_prob: float, ai_prob: float) -> tuple:
    if real_prob >= THRESHOLD:
        return 1, "real"
    else:
        return 0, "AI"

def generate_alert_message(alert: int, ai_prob: float) -> str:
    if alert == 0:
        return "No alert"
    return f"{ai_prob*100:.2f}% generated by AI "
